### ISSUE TITLE
Welcome

### ISSUE THREAD

**Issue by radicalmind** [radicalmind/xeon#1]
__02 June 2017__

Hello Gophers and other developers,
this is the welcome page for newcomers!

Xeon was in "private place" for a lot, I decided to publish it here in order to make it even better with your help.

Feature requests (except for those that already exist, i.e gorm), code reviews and any fixes and improvements to the code are welcomed after a deep discussion with the rest of the community!

### Versioning

Unlike [semantic versioning](http://semver.org/), 
this project's versions are aligned with the current golang version number. Xeon will be always up-to-date and will introduce new things and new tech trends on each of its releases. 

New versions should be developed to their own github branches, i.e v1.8.3, v1.9.0 etc...
A new version will be pushed to the master whenever it's ready(implemented, reviewed and tested) and adapted the new golang's release features.

Current version is: **1.8.3** 

The next version will be published when go 1.9 will be released (soon).

### TODO

Although the framework was well-tested at production level, there are some missing parts:
- [ ] Complete the whole source-code's comments
- [ ] Fill the doc.go with the framework's documentation
- [ ]  Unit with Black-box tests instead of my local white-box tests

> This is an exception of "submitting an issue" rules 🤙

**Comment by radicalmind** [comment]
## Link with Iris

Many of you may think that this project is just an improvement [Iris](https://github.com/kataras/iris) version because of its easy-API's similiatiries, but that's all.
It's true that this project has a lot of API and performance similarities with the Golang's web framework,  [Iris](https://github.com/kataras/iris).

But why?
No, I didn't "stole" Iris' codebase neither Iris from Xeon. 

Xeon seems to be newest than Iris, but this is not entirely the truth, because author of Iris and me worked internally in the same place, we started from the same codebase at the same time, a year ago.

Back then I wasn't really excited, about his opinions about "open-source idea" and his action to publish the project for free. Iris was a result of hundreds of hours of free-work instead of a paid one, but he convinced me (he's a real diplomat!) to do it.

Of course that Iris' version has nothing to do with this big monster that Iris became later, credits to @kataras. Back then it was more like a router instead of a web framework.

Objectively, Iris is a successor. It succeed to be one of the most trending project on github globe, with:
- 1 contributor
- ~7.000 github stars
- ~400 github watchers
- ~500 github forks
- almost the majority of golang community's friendly tweets and articles
- top #25 on HackerNews over multiple times
- a lot of donations by independent developers and freelancers

So, I decided to take some months off of my job. Take the Iris as it is now and transform it to a next-level-tool.
At __Friday, 02 June 2017__ I published my code with all the enchantments implemented, tested at production-level and reviewed by [@kataras](https://github.com/kataras) himself, he sent me the OK signal to push it with his approval and resigned from any copyrights. I am very thankful for this. I wouldn't be able to develop Xeon without his help and his mental support.

As you will see Xeon has an entirely different structure, some Iris' features that I thought are not nessecary are being removed. 
A lot of improvements and fixes added, its development will be **not** connected with Iris from now and on.

Xeon is a different and unique framework. 

I hope Xeon will get the community's support that Iris had from its zero day!

**Comment by radicalmind** [comment]
## Link with Iris

Many of you may think that this project is just an improvement [Iris](https://github.com/kataras/iris) version because of its easy-API's similiatiries, but that's all.
It's true that this project has a lot of API and performance similarities with the Golang's web framework,  [Iris](https://github.com/kataras/iris).

But why?
No, I didn't "stole" Iris' codebase neither Iris from Xeon. 

Xeon seems to be newest than Iris, but this is not entirely the truth, because author of Iris and me worked internally in the same place, we started from the same codebase at the same time, a year ago.

Back then I wasn't really excited, about his opinions about "open-source idea" and his action to publish the project for free. Iris was a result of hundreds of hours of free-work instead of a paid one, but he convinced me (he's a real diplomat!) to do it.

Of course that Iris' version has nothing to do with this big monster that Iris became later, credits to @kataras. Back then it was more like a router instead of a web framework.

Objectively, Iris is a successor. It succeed to be one of the most trending project on github globe, with:
- 1 contributor
- ~7.000 github stars
- ~400 github watchers
- ~500 github forks
- almost the majority of golang community's friendly tweets and articles
- top #25 on HackerNews over multiple times
- a lot of donations by independent developers and freelancers

So, I decided to take some months off of my job. Take the Iris as it is now and transform it to a next-level-tool.
At __Friday, 02 June 2017__ I published my code with all the enchantments implemented, tested at production-level and reviewed by [@kataras](https://github.com/kataras) himself, he sent me the OK signal to push it with his approval and resigned from any copyrights. I am very thankful for this. I wouldn't be able to develop Xeon without his help and his mental support.

As you will see Xeon has an entirely different structure, some Iris' features that I thought are not nessecary are being removed. 
A lot of improvements and fixes added, its development will be **not** connected with Iris from now and on.

Please understand that Xeon is a different and unique framework, see its code and its features for proof. 

Xeon It's based on Iris but it's not Iris, because its public end-developer API is similar it doesn't mean that this is the same. Xeon has a small performance adv over Iris. You can test it with tools like `ab`, `bombardier` etc...

I hope Xeon will get the community's support that Iris had from its zero day!
